version: "3.9"
services:
#   nginx:
#     build:
#       context: .
#       dockerfile: "Dockerfile.nginx"
#     container_name: test_task_nginx
#     ports:
#       - 80:80
#       - 443:443
#     links:
#       - test_task

  db:
    image: postgres:15
    container_name: test_task_db
    volumes:
      - postgresdata:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432

  test_task:
    image: test_task
    build:
      context: .
    container_name: test_task
    env_file:
      - .env
    depends_on:
      - db
    command: ["/test_task/docker/app.sh"]
    ports:
      - 8000:8000

volumes:
  postgresdata: